"""Refit β(ln σ) on N=512 nocut snapshots — universality test for the v5 law.

Loads the ``N512_nocutoff_lowa.npz`` snapshots generated by
``gen_N512_nocut_lowa.py``, computes PM moments at each a, scans the
**v5** cascade β grid with parabolic S₃-matching refinement, and fits
``β = β₀ + β_ln · ln σ``.

N=256 v5 gave β = -0.057 + 0.052·ln σ (rms = 0.0016). At N=512 nocut
the same a values give larger σ (PM-resolution-dependent) — so the
snapshots probe the law at shifted σ points. If universal, the fit
line stays the same; β_best values slide along it.
"""

import json, time

import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import jax, jax.numpy as jnp

from discodj.analysis import load_sim, deformation_gradient_jacobian
from discodj.analysis.spectral_slope import reconstruct_pk
from discodj.cascade import fem_cascade_v5


N_CAS, N_STEPS, BOXSIZE = 64, 10, 250.0
SEEDS = 5
A_LIST = [0.03, 0.05, 0.07, 0.10]
N_PM = 512


def Jmom(J):
    a = np.asarray(J).ravel()
    m = a.mean(); d = a - m
    v = float(np.mean(d * d))
    s3 = float(np.mean(d**3) / max(v, 1e-30)**1.5)
    return float(m), v, s3


def scan(sigma2, pk_k, pk_Pk, betas):
    vs, S3s = np.empty_like(betas), np.empty_like(betas)
    for i, b in enumerate(betas):
        vi, si = [], []
        for s in range(SEEDS):
            r = fem_cascade_v5(sigma2=sigma2, n_steps=N_STEPS, N=N_CAS,
                               boxsize=BOXSIZE, key=jax.random.PRNGKey(7100 + s),
                               g_T=0.0, alpha_nl=0.0, beta_nl=float(b), gamma_nl=0.0,
                               pk_k=pk_k, pk_Pk=pk_Pk,
                               method="midpoint", use_abs_J=True)
            jax.block_until_ready(r.J)
            _, v, s3 = Jmom(r.J)
            vi.append(v); si.append(s3)
        vs[i] = np.mean(vi); S3s[i] = np.mean(si)
    return vs, S3s


def refine_parabola(betas, loss):
    imin = int(np.argmin(loss))
    if imin == 0 or imin == len(betas) - 1:
        return float(betas[imin])
    b = betas[imin - 1:imin + 2]; L = loss[imin - 1:imin + 2]
    denom = (L[0] - 2 * L[1] + L[2])
    if abs(denom) < 1e-12:
        return float(betas[imin])
    offset = 0.5 * (L[0] - L[2]) / denom * (b[1] - b[0])
    return float(b[1] + offset)


def pick_beta_grid(sigma2):
    """Scan a tight range around the v5 law prediction (β ≈ -0.057 + 0.052·ln σ)."""
    ln_sig = 0.5 * np.log(sigma2)
    b_guess = -0.057 + 0.052 * ln_sig
    return np.arange(b_guess - 0.20, b_guess + 0.20 + 1e-9, 0.01)


def main():
    rows = []
    t_all = time.time()
    for a_pm in A_LIST:
        snap = load_sim(N_PM, "nocutoff", a=a_pm)
        print(f"  loading a={a_pm}  snap.a={snap.a:.2f}  N={snap.N}")
        G_pm, J_pm = deformation_gradient_jacobian(snap)
        s2 = float(jnp.var(jnp.einsum("...ii->...", G_pm)))
        _, v_pm, S3_pm = Jmom(J_pm)
        k_np, Pk_np = reconstruct_pk(snap)
        pk_k, pk_Pk = jnp.asarray(k_np), jnp.asarray(Pk_np)
        betas = pick_beta_grid(s2)
        t0 = time.time()
        vs_cas, S3s_cas = scan(s2, pk_k, pk_Pk, betas)
        loss_S3 = (S3s_cas - S3_pm)**2
        b_S3 = refine_parabola(betas, loss_S3)
        dt = time.time() - t0
        print(f"  a={a_pm:.2f}  σ²={s2:.4f}  S₃_PM={S3_pm:+.3f}  "
              f"β_best(S₃)={b_S3:+.3f}  β-grid [{betas[0]:+.2f},{betas[-1]:+.2f}]  ({dt:.0f}s)")
        rows.append(dict(a=float(snap.a), sigma2=s2, S3_PM=S3_pm, v_PM=v_pm,
                         beta_best_S3=b_S3,
                         betas=betas.tolist(),
                         sigma2_J_cas=vs_cas.tolist(),
                         S3_cas=S3s_cas.tolist()))

    # Linear fit
    ln_sig = np.array([0.5 * np.log(r["sigma2"]) for r in rows])
    y = np.array([r["beta_best_S3"] for r in rows])
    A = np.column_stack([np.ones_like(ln_sig), ln_sig])
    coefs, *_ = np.linalg.lstsq(A, y, rcond=None)
    b0, b_ln = float(coefs[0]), float(coefs[1])
    resid = y - (b0 + b_ln * ln_sig)
    rms = float(np.sqrt(np.mean(resid**2)))
    SSx = float(np.sum((ln_sig - ln_sig.mean())**2))
    se_slope = float(np.sqrt((resid**2).sum() / max(len(ln_sig) - 2, 1) / SSx))
    se_intercept = float(se_slope * np.sqrt((ln_sig**2).mean()))

    print(f"\n[N_PM=512, N_CAS={N_CAS}, v5, S₃-only]  "
          f"β = {b0:+.4f}(±{se_intercept:.4f}) + ({b_ln:+.4f}±{se_slope:.4f})·ln σ   rms = {rms:.4f}")
    # Compare to N=256 v5 reference law: β = -0.057 + 0.052·ln σ
    ref_b0, ref_bln = -0.0570, 0.0518
    print(f"  vs N=256 v5 law: Δintercept = {b0 - ref_b0:+.4f}  "
          f"({(b0-ref_b0)/max(se_intercept,1e-9):+.2f}σ)")
    print(f"  vs N=256 v5 law: Δslope     = {b_ln - ref_bln:+.4f}  "
          f"({(b_ln-ref_bln)/max(se_slope,1e-9):+.2f}σ)")

    # Predicted-vs-measured β via the N=256 v5 law
    print(f"\n  N=256 v5 law: β_pred = -0.057 + 0.052·ln σ")
    print(f"  {'a':>5} {'σ':>6}  {'β_pred':>8}  {'β_meas':>8}  {'Δβ':>8}")
    for r in rows:
        sig = float(np.sqrt(r["sigma2"]))
        b_pred = ref_b0 + ref_bln * np.log(sig)
        print(f"  {r['a']:5.2f} {sig:6.3f}  {b_pred:+8.4f}  {r['beta_best_S3']:+8.4f}  "
              f"{r['beta_best_S3'] - b_pred:+8.4f}")

    # Plot alongside N=256 v5 result
    fig, ax = plt.subplots(figsize=(8, 5.5))
    ax.errorbar(ln_sig, y, yerr=rms, fmt="o", ms=10, color="tab:red",
                label=f"N_PM=512 v5 (this run)")
    xs = np.linspace(-2.5, 0.5, 100)
    ax.plot(xs, b0 + b_ln * xs, "-", color="tab:red", alpha=0.5,
            label=f"N=512 v5 fit: β = {b0:+.3f} + ({b_ln:+.3f})·ln σ")
    # N=256 v5 reference line
    ax.plot(xs, ref_b0 + ref_bln * xs, "--", color="black", lw=1.5,
            label=fr"N=256 v5 law: $\beta = {ref_b0:+.3f} + ({ref_bln:+.3f})\ln\sigma$")

    # Overlay N=256 v5 points if available
    try:
        d256 = json.load(open("docs/beta_nocut_v5.json"))
        ln_s_256 = np.array([0.5 * np.log(r["sigma2"]) for r in d256["rows"]])
        y_256 = np.array([r["beta_best_S3"] for r in d256["rows"]])
        ax.errorbar(ln_s_256, y_256, yerr=d256.get("rms", 0.002), fmt="s",
                    ms=8, color="tab:blue", alpha=0.8,
                    label="N_PM=256 v5 (prior)")
    except FileNotFoundError:
        pass

    for r in rows:
        ax.annotate(f"a={r['a']:.2f}",
                    (0.5 * np.log(r["sigma2"]), r["beta_best_S3"]),
                    fontsize=9, alpha=0.9, xytext=(5, 5),
                    textcoords="offset points", color="tab:red")

    ax.set_xlabel(r"$\ln \sigma$")
    ax.set_ylabel(r"$\beta_{\rm nl, best}$ (S₃ match)")
    ax.set_title(r"Universality test: $\beta(\ln\sigma)$ at N_PM=256 vs N_PM=512 (nocut)")
    ax.grid(alpha=0.3); ax.legend(fontsize=9, loc="lower right")
    fig.tight_layout()
    fig.savefig("docs/beta_vs_logsigma_N512_univ.png", dpi=130)
    print(f"\nSaved docs/beta_vs_logsigma_N512_univ.png")

    with open("docs/beta_nocut_N512.json", "w") as f:
        json.dump(dict(N_PM=N_PM, N_CAS=N_CAS, SEEDS=SEEDS,
                       intercept=b0, slope=b_ln, rms=rms,
                       se_slope=se_slope, se_intercept=se_intercept,
                       rows=rows), f, indent=2)
    print("Saved docs/beta_nocut_N512.json")
    print(f"Total wall time: {time.time()-t_all:.0f}s")


if __name__ == "__main__":
    main()
